[workspace]
resolver = "2"
members = [
    "winia",
    "skiwin",
    "proc-macro", "winia_test", "interpolator_generator", "ai_chat", "winia-video"]

default-members = ["winia"]

[workspace.dependencies]
winit = "0.30.12"
skia-safe = "0.87.0"
skia-bindings = "0.87.0"
parking_lot = "0.12.4"
