[workspace]
resolver = "2"
members = [
    "example",
    "winia",
    "skiwin",
    "material_color_utilities",
    "exmaple2",
    "winia/proc-macro"]

exclude = ["winia"]

[workspace.dependencies]
winit = "0.30.8"
skia-safe = "0.81.0"
parking_lot = "0.12.3"
