[workspace]
resolver = "2"
members = [
    "winia",
    "winia-macros",
    "skiwin",
    "material-shapes",
]

[workspace.metadata.orphan-gc]
enabled = true
dry-run = false
inner-wrapper = "sccache"
pending-sweeps-per-compile = 4

[workspace.dependencies]
winit = "0.31.0-beta.2"
skia-safe = "0.99.0"
skia-bindings = "0.99.0"
material-shapes = { path = "material-shapes", features = ["shape_util"] }
parking_lot = "0.12"
log = "0.4"
thiserror = "2"
letclone = "0.3.0"
