[package]
name = "winia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["vulkan"]
vulkan = ["skiwin/vulkan"]
gl = ["skiwin/gl"]

[dependencies]
skiwin = {path = "../skiwin"}
lazy_static = "1.5.0"
raw-window-handle = "0.6.2"
env_logger = "0.11.5"
#icu = "1.5.0"
bitflags = "2.6.0"
bezier-rs = "0.4.0"
#reqwest = {version = "0.12.9",features = ["blocking"]}
material_color_utilities = {path = "../material_color_utilities" }
#skia-bindings = "0.80"
unicode-segmentation = "1.12.0"
bimap = "0.6.3"

[target.'cfg(target_os = "linux")'.dependencies]
winit = {workspace = true, features = ["rwh_06"]}
skia-safe = {workspace = true, features = ["textlayout","embed-icudtl","svg"]}

[target.'cfg(target_os = "windows")'.dependencies]
winit = {workspace = true, features = ["rwh_06"]}
skia-safe = {workspace = true, features = ["textlayout","embed-icudtl","svg","d3d","gl"]}
##winapi = {version = "0.3.9", features = ["winreg", "dwmapi", "windef", "winuser"] }

[target.'cfg(target_os = "android")'.dependencies]
skia-safe = {workspace = true, features = ["all-linux"]}
winit = {workspace = true, features = ["rwh_06", "android-native-activity"]}
#android_logger = "0.14.1"