use regex::Regex;
use crate::cubic::Cubic;
use crate::feature::Feature;
use crate::utils::require;

/**
 * The [FeatureSerializer] is used to both serialize and parse [Feature] objects. This is beneficial
 * when you want to re-use [RoundedPolygon] objects created by [SvgPathParser], as parsing
 * serialized [Feature] objects is more performant than using the svg path import.
 *
 * **Example:**
 *
 * ```kotlin
 * // Do the following three *once*
 * val triangleSVGPath: String = "M0,0 0.5,1 1,0Z"
 * val triangleFeatures: List<Feature> = SvgPathParser.parseFeatures(triangleSVGPath)
 * val serializedTriangle: String = FeatureSerializer.serialize(triangleFeatures)
 *
 * // Parse the serialized triangle features in your production code.
 * // You can adjust them (e.g. the type) however you want before parsing.
 * val features: List<Feature> = FeatureSerializer.parse(serializedTriangle)
 * val triangle: RoundedPolygon = RoundedPolygon(features, centerX = 0.5f, centerY = 0.5f)
 * Morph(triangle, ...)
 * ```
 */
pub struct FeatureSerializer;
impl FeatureSerializer {
    /**
    * Serializes a list of [Feature] objects into a string representation, adhering to version
    * 1 of the feature serialization format.
    *
    * **Format:**
    * 1. **Version Identifier:** A 'V' followed by the version number (e.g., 'V1').
    * 2. **Feature Serialization:** Each [Feature] is serialized individually and concatenated.
    *     - **Feature Tag:** A single-character tag identifies the feature type:
    *         - 'n': Edge
    *         - 'x': Convex Corner
    *         - 'o': Concave Corner
    *     - **Cubic Serialization:** Each [Cubic] within a feature is serialized as a sequence
    *       of comma-separated x,y coordinates. Subsequent cubics within a feature omit their
    *       first anchor points, as they're identical to their predecessors' last anchor
    *       points.
    *
    * **Example:** Given two features:
    * - An edge with one [Cubic]: { (0, 0), (1, 1), (2, 2), (3, 3) }
    * - A convex corner with two [Cubic] objects: { (0, 0), (1, 1), (2, 2), (3, 3) }, { (3, 3),
    *   (4, 4), (5, 5), (6, 6) }
    *
    * The serialized string would be:
    * ```text
    * V1 n 0,0, 1,1, 2,2, 3,3  x 0,0, 1,1, 2,2, 3,3, 4,4, 5,5, 6,6
    * ```
    *
    * @param features The list of [Feature] objects to serialize.
    * @return The serialized string representation of the [features]
    */
    pub fn serialize(features: &Vec<Feature>) -> String {
        let mut result = String::new();
        result.push_str("V1");
        for feature in features.iter() {
            result.push_str(Self::serialize_feature(feature).as_str());
        }
        result
    }


    /**
     * Parses a serialized string representation of [Feature] into their object representations,
     * adhering to version 1 of the feature serialization format.
     *
     * The serialized string must adhere to the format generated by
     * [FeatureSerializer.serialize]. This format consists of:
     * 1. **Version Identifier:** A 'V' followed by the version number (e.g., 'V1').
     * 2. **Feature Serialization:** Each [Feature] is serialized individually and concatenated.
     *     - **Feature Tag:** A single-character tag identifies the feature type:
     *         - 'n': Edge
     *         - 'x': Convex Corner
     *         - 'o': Concave Corner
     *         - Any other tags unknown to version 1 will default to an edge interpretation.
     *     - **Cubic Serialization:** Each [Cubic] within a feature is serialized as a sequence
     *       of comma-separated x,y coordinates. Subsequent cubics within a feature omit their
     *       first anchor points, as they're identical to their predecessors' last anchor
     *       points.
     *
     * **Note:** The current version (1) of the serialization format is stable. However, future
     * versions may introduce incompatible changes with version 1. The default behavior for
     * unknown or missing versions will be version 1 parsing. If you have a later version
     * string, update the library to the latest version.
     *
     * @param serializedFeatures The serialized [Feature] objects in a concatenated String.
     * @return A list of parsed [Feature] objects, corresponding to the serialized input.
     * @throws IllegalArgumentException - if a serialized string lacks sufficient points to
     *   create [Cubic] objects with
     * @throws IllegalArgumentException - if no feature tags could be found
     * @throws NumberFormatException - if the [Cubic]s' coordinates aren't valid representations
     *   of numbers.
     */
    pub fn parse(serialized_features: &str) -> Vec<Feature> {
        let version_regex = Regex::new("^\\s*V(\\d+)").unwrap();
        let version = version_regex.find_iter(serialized_features);
        let tags_search_start = if let Some(m) = version.into_iter().next() {
            m.end()
        } else {
            0
        };
        // let tags = Regex::new("[a-zA-Z]").unwrap().find_iter(&serialized_features[tags_search_start..]);
        let tag_regex = Regex::new("[a-zA-Z]").unwrap();
        let tags = tag_regex.find_iter(&serialized_features[tags_search_start..]);
        // required(
        //     tags.count() > 0,
        //     "No feature tags found in serialized features."
        // );
        let mut features: Vec<Feature> = Vec::new();
        let tag_positions: Vec<usize> = tags.map(|m| m.start() + tags_search_start).collect();
        for i in 0..tag_positions.len() {
            let start_index = tag_positions[i];
            let end_index = if i + 1 < tag_positions.len() {
                tag_positions[i + 1]
            } else {
                serialized_features.len()
            };
            features.push(
                Self::parse_feature(
                    serialized_features,
                    start_index,
                    end_index
                )
            );
        }
        features
    }
    fn serialize_feature(feature: &Feature) -> String {
        let mut result = String::new();
        match feature {
            Feature::Edge(edge) => {
                result.push(Self::EDGE_CHAR);
                result.push_str(Self::serialize_cubics(&edge.cubics).as_str());
            }
            Feature::Corner(corner) => {
                let convex_flag = if corner.convex { Self::CONVEX_CORNER_CHAR } else { Self::CONCAVE_CORNER_CHAR };
                result.push(convex_flag);
                result.push_str(Self::serialize_cubics(&corner.cubics).as_str());
            }
        }
        result
    }

    fn join_to<T>(
        items: &[T],
        separator: &str,
        limit: impl Into<Option<usize>>,
        transform: impl Fn(&T) -> String,
    ) -> String {
        let limit = limit.into();
        let mut result = String::new();
        let mut count = 0;
        for item in items.iter() {
            count += 1;
            if count > 1 {
                result.push_str(separator);
            }
            if let Some(limit) = limit && count <= limit {
                result.push_str(transform(item).as_str());
            } else if limit.is_none() {
                result.push_str(transform(item).as_str());
            } else {
                break;
            }
        }
        result
    }

    fn serialize_cubics(cubics: &Vec<Cubic>) -> String {
        fn remove_trailing_zeroes(f: f32) -> String {
            let s = format!("{}", f);
            if s.contains('.') {
                s.trim_end_matches('0').trim_end_matches('.').to_string()
            } else {
                s
            }
        }
        let mut result = String::new();
        for cubic in cubics.iter() {
            result.push_str(
                Self::join_to(&cubic.points, Self::SEPARATOR.to_string().as_str(), 6, |p|{
                    remove_trailing_zeroes(*p)
                }).as_str()
            )
        }
        let last_cubic = cubics.last().unwrap();
        let last_x = remove_trailing_zeroes(last_cubic.anchor_1_x());
        let last_y = remove_trailing_zeroes(last_cubic.anchor_1_y());
        result.push_str(format!("{}{}{}", last_x, Self::SEPARATOR, last_y).as_str());
        result
    }

    fn parse_feature(
        serialized: &str,
        start_index: usize,
        end_index: usize,
    ) -> Feature {
        let feature_tag = &serialized[start_index..start_index+1];
        let edge_str = String::from(Self::EDGE_CHAR);
        let convex_str = String::from(Self::CONVEX_CORNER_CHAR);
        let concave_str = String::from(Self::CONCAVE_CORNER_CHAR);
        if feature_tag == edge_str {
            Feature::edge(
                Self::parse_cubics(serialized, start_index + 1, end_index)
            )
        } else if feature_tag == convex_str {
            Feature::corner(
                Self::parse_cubics(serialized, start_index + 1, end_index),
                true
            )
        } else if feature_tag == concave_str {
            Feature::corner(
                Self::parse_cubics(serialized, start_index + 1, end_index),
                false
            )
        } else {
            // default to edge for unknown tags
            Feature::edge(
                Self::parse_cubics(serialized, start_index + 1, end_index)
            )
        }
    }

    fn parse_cubics(serialized: &str, start_index: usize, end_index: usize) -> Vec<Cubic> {
        // this is a very low level implementation to avoid allocations as the parsing of
        // serialized shapes can happen per frame. the functional equivalent would be
        // val points = serialized.serialized.substring(startIndex, endIndex)
        //                              .split(separator).map { it.toFloat() }
        // return points.windowed(8, step = 6).map { Cubic(it.toFloatArray()) }

        let window_size = 8;
        let window_step = 6;

        let mut point_start = start_index;
        let mut point_end = start_index;
        let mut point_count = 0;
        let mut points: Vec<f32> = Vec::with_capacity(window_size);

        // helper values saved in top level to avoid new allocations
        let mut next_start_x = 0.0;
        let mut next_start_y = 0.0;
        let mut cubics: Vec<Cubic> = Vec::new();

        let separator_str = Self::SEPARATOR.to_string();
        while point_end < end_index {
            // the number is still going, move to next character
            if serialized[point_end..point_end+1] != separator_str {
                point_end += 1;
                continue;
            }
            // a number ended, add it to the points array and increase count
            points.push(serialized[point_start..point_end].parse::<f32>().unwrap());
            point_count += 1;

            // if we closed our window, parse it to cubic and reset values for the
            // next window
            if point_count == window_size {
                cubics.push(Cubic::from_array(&points));
                // end of this cubic is start of next. we reset the points array
                // because cubics save references to them and we would otherwise
                // need to deep copy the array to avoid the same reference across all cubics
                next_start_x = points[window_size - 2];
                next_start_y = points[window_size - 1];
                points = Vec::with_capacity(window_size);
                points[0] = next_start_x;
                points[1] = next_start_y;
                point_count -= window_step;
            }

            point_end += 1;
        }
        require(
            point_count + 1 == window_size,
            {
                let needed_points = if serialized[point_start..end_index].parse::<f32>().is_ok() {
                    window_size - (point_count + 1)
                } else {
                    window_size - point_count
                };
                format!(
                    "Received a feature with an insufficient amount of numbers for substring '{}'. Wanted to create {} continuous cubic bezier curves for this feature, but the last one is missing $neededPoints more numbers separated by '{}'.",
                    &serialized[start_index..end_index],
                    cubics.len() + 1,
                    Self::SEPARATOR
                )
            }
        );
        // add last point and last cubic
        points.insert(window_size -1, serialized[point_start..end_index].parse::<f32>().unwrap());
        cubics.push(Cubic::from_array(&points));
        cubics
    }

    const SEPARATOR: char = ',';
    const CONVEX_CORNER_CHAR: char = 'x';
    const CONCAVE_CORNER_CHAR: char = 'o';
    const EDGE_CHAR: char = 'n';
    const FEATURE_TAG_ARRAY: [char; 3] = [
        Self::EDGE_CHAR,
        Self::CONVEX_CORNER_CHAR,
        Self::CONCAVE_CORNER_CHAR,
    ];
}