use std::ops::MulAssign;
use crate::cubic::PointTransformer;
use crate::utils::require;

#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct Point(pub f32, pub f32);
impl Point {
    pub fn new(x: f32, y: f32) -> Point {
        Point(x, y)
    }
    pub fn rotate_90(&self) -> Point {
        Point(-self.1, self.0)
    }
    pub fn x(&self) -> f32 {
        self.0
    }
    pub fn y(&self) -> f32 {
        self.1
    }

    /// The magnitude of the Point, which is the distance of this point from (0, 0).
    /// If you need this value to compare it to another Point's distance, consider using [`get_distance_squared`](Point::get_distance_squared) instead, since it is cheaper to compute.
    pub fn get_distance(&self) -> f32 {
        (self.0 * self.0 + self.1 * self.1).sqrt()
    }
    /// The square of the magnitude (which is the distance of this point from (0, 0)) of the Point.
    /// This is cheaper than computing the [get_distance](Point::get_distance) itself.
    pub fn get_distance_squared(&self) -> f32 {
        self.0 * self.0 + self.1 * self.1
    }
    pub fn dot_product(&self, other: Point) -> f32 {
        self.0 * other.0 + self.1 * other.1
    }

    pub fn dot_product_xy(&self, x: f32, y: f32) -> f32 {
        self.0 * x + self.1 * y
    }

    /// Compute the Z coordinate of the cross product of two vectors, to check if the second vector is going clockwise ( > 0 ) or counterclockwise (< 0) compared with the first one. It could also be 0, if the vectors are co-linear.
    pub fn clockwise(&self, other: &Point) -> bool {
        self.0 * other.1 - self.1 * other.0 > 0.0
    }

    /// Returns unit vector representing the direction to this point from (0, 0)
    pub fn get_direction(&self) -> Point {
        let d = self.get_distance();
        require(d > 0.0, "Can't get the direction of a 0-length vector");
        *self / d
    }

    pub fn transformed(&self, f: &PointTransformer) -> Point {
        f(self.0, self.1)
    }
}

impl std::ops::Neg for Point {
    type Output = Point;
    fn neg(self) -> Point {
        Point(-self.0, -self.1)
    }
}

impl std::ops::Sub for Point {
    type Output = Point;

    fn sub(self, rhs: Self) -> Self::Output {
        Point(self.0 - rhs.0, self.1 - rhs.1)
    }
}

impl std::ops::Add for Point {
    type Output = Point;

    fn add(self, rhs: Self) -> Self::Output {
        Point(self.0 + rhs.0, self.1 + rhs.1)
    }
}

impl std::ops::Mul<f32> for Point {
    type Output = Point;
    fn mul(self, rhs: f32) -> Self::Output {
        Point(self.0 * rhs, self.1 * rhs)
    }
}

impl std::ops::Div<f32> for Point {
    type Output = Point;
    fn div(self, rhs: f32) -> Self::Output {
        Point(self.0 / rhs, self.1 / rhs)
    }
}

impl std::ops::Rem<f32> for Point {
    type Output = Point;
    fn rem(self, rhs: f32) -> Self::Output {
        Point(self.0 % rhs, self.1 % rhs)
    }
}

impl MulAssign<f64> for Point {
    fn mul_assign(&mut self, rhs: f64) {
        self.0 *= rhs as f32;
        self.1 *= rhs as f32;
    }
}

impl MulAssign<f32> for Point {
    fn mul_assign(&mut self, rhs: f32) {
        self.0 *= rhs;
        self.1 *= rhs;
    }
}

impl MulAssign<i32> for Point {
    fn mul_assign(&mut self, rhs: i32) {
        self.0 *= rhs as f32;
        self.1 *= rhs as f32;
    }
}
impl MulAssign<u32> for Point {
    fn mul_assign(&mut self, rhs: u32) {
        self.0 *= rhs as f32;
        self.1 *= rhs as f32;
    }
}

/// Linearly interpolate between two [`Point`]s.
///
/// The `fraction` argument represents position on the timeline, with `0.0` meaning that the
/// interpolation has not started, returning `start` (or something equivalent to `start`),
/// `1.0` meaning that the interpolation has finished, returning `stop` (or something equivalent
/// to `stop`), and values in between meaning that the interpolation is at the relevant point on
/// the timeline between `start` and `stop`. The interpolation can be extrapolated beyond `0.0`
/// and `1.0`, so negative values and values greater than `1.0` are valid (and can easily be
/// generated by curves).
///
/// Values for `fraction` are usually obtained from an `Animation<f32>`, such as an
/// `AnimationController`.
pub fn interpolate(start: Point, stop: Point, fraction: f32) -> Point {
    Point(
        crate::utils::interpolate(start.0, stop.0, fraction),
        crate::utils::interpolate(start.1, stop.1, fraction),
    )
}