name: Build Example

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  windows-build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --package winia_test
      - name: ls
        run: ls target/debug
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-windows
          path: target/debug/winia_test.exe